---
kind: pipeline
type: docker
name: build-linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: golang:1.14
  environment:
    CGO_ENABLED: "0"
  commands:
  - go build -o release/linux/amd64/acmeca ./cmd/acmeca.go
  - setcap 'cap_net_bind_service=ep' release/linux/amd64/acmeca
  - echo "edge-linux-amd64,${DRONE_COMMIT:0:8}-linux-amd64" | tee .tags
- name: publish
  image: plugins/docker
  settings:
    daemon_off: false
    repo: ${DRONE_REPO}
    dockerfile: docker/Dockerfile.linux.amd64
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD

---
kind: pipeline
type: docker
name: build-linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: golang:1.14
  environment:
    CGO_ENABLED: "0"
  commands:
  - go build -o release/linux/arm64/acmeca ./cmd/acmeca.go 
  - setcap 'cap_net_bind_service=ep' release/linux/arm64/acmeca
  - echo "edge-linux-arm64,${DRONE_COMMIT:0:8}-linux-arm64" | tee .tags
- name: publish
  image: plugins/docker
  settings:
    daemon_off: false
    repo: ${DRONE_REPO}
    dockerfile: docker/Dockerfile.linux.arm64
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD

---
kind: pipeline
type: docker
name: build-linux-arm

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: golang:1.14
  environment:
    CGO_ENABLED: "0"
  commands:
  - go build -o release/linux/arm/acmeca ./cmd/acmeca.go 
  - setcap 'cap_net_bind_service=ep' release/linux/arm/acmeca
  - echo "edge-linux-arm,${DRONE_COMMIT:0:8}-linux-arm" | tee .tags
- name: publish
  image: plugins/docker
  settings:
    daemon_off: false
    repo: ${DRONE_REPO}
    dockerfile: docker/Dockerfile.linux.arm
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD

---
kind: pipeline
type: docker
name: notifications

platform:
  os: linux
  arch: amd64
steps:
- name: manifest
  image: plugins/manifest
  settings:
    username: 
      from-secret: DOCKER_USERNAME
    password: 
      from-secret: DOCKER_PASSWORD
    ignore_missing: true
    target: $DRONE_REPO:${DRONE_COMMIT:0:8}
    template: $DRONE_REPO:${DRONE_COMMIT:0:8}-OS-ARCH
    platforms:
      - linux/amd64
      - linux/arm
      - linux/arm64

depends_on:
- build-linux-amd64
- build-linux-arm64
- build-linux-arm