---
version: '3.7'

services:
  acme:
    image: cblomart/acmeca:1f90852b
    environment:
    - CA
    - SECRET=Sup3rS3cr3t
    - DOMAINS=.lan
    ports:
    - 8443:8443
    volumes:
    - acmecavar:/var/acmeca/
    - acmecaetc:/etc/acmeca/

volumes:
  acmecavar:
    external: true
  acmecaetc:
    external: true