---
version: '3.7'

services:
  acme:
    image: cblomart/acmeca:edge
    environment:
    - CA=true
    - SECRET=Sup3rS3cr3t
    - DOMAINS=.lan
    ports:
    - 8443:8443
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8443/health"]
      retries: 10
    volumes:
    - acmecavar:/var/acmeca/
    - acmecaetc:/etc/acmeca/

volumes:
  acmecavar:
    external: true
  acmecaetc:
    external: true