#!/bin/bash

# function to check the existance of tags
function docker_tag_exists() {
    curl --silent -f -lSL https://index.docker.io/v1/repositories/$1/tags/$2 > /dev/null
}

repository="cblomart/acmeca"

if ! docker_tag_exists $repository amd64; then
    echo "$repository:amd64 does not exist"
    exit 
fi

if ! docker_tag_exists $repository arm64v8; then
    echo "$repository:arm64v8 does not exist"
    exit 
fi


# Use manifest-tool to create the manifest, given the experimental
# "docker manifest" command isn't available yet on Docker Hub.

curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.2/manifest-tool-linux-amd64
chmod +x manifest-tool

./manifest-tool push from-spec multi-arch-manifest.yaml